version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.1.0-management
    container_name: rmq
    hostname: rmq
    ports:
      - "5673:5672"   # AMQP 프로토콜 포트
      - "15673:15672" # Management UI 포트
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
    name: rabbitmq_data