### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8081/test

###
POST http://localhost:8081/api/messages/actions/send
Content-Type: application/json

"message~~!!⭐️"